import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const cormorantBold = localFont({
  src: "./fonts/CormorantGaramond-Bold.ttf",
  variable: "--font-cormorant-bold",
  weight: "700",
});
const cormorantRegular = localFont({
  src: "./fonts/CormorantGaramond-Regular.ttf",
  variable: "--font-cormorant-regular",
  weight: "400",
});
const monteserratRegular = localFont({
  src: "./fonts/Montserrat-VariableFont_wght.ttf",
  variable: "--font-monteserrat",
  weight: "400",
});

export const metadata: Metadata = {
  title: "LearnSnap",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cormorantBold.variable} ${cormorantRegular.variable} ${monteserratRegular.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
